# Generated by Django 3.0.6 on 2023-11-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato1', models.CharField(max_length=100)),
                ('dato2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MLF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato1', models.CharField(max_length=100)),
                ('dato2', models.IntegerField()),
            ],
        ),
    ]
