# Generated by Django 3.0.6 on 2023-11-27 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_datos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='campo3',
        ),
        migrations.AddField(
            model_name='datos',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datos',
            name='campo1',
            field=models.CharField(max_length=255),
        ),
    ]
