# Generated by Django 3.0.6 on 2023-11-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20231127_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='usuario',
            field=models.CharField(max_length=150),
        ),
    ]
