# Generated by Django 3.0.6 on 2023-11-27 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0008_datos_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='licuefac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('campo1', models.CharField(max_length=255)),
                ('campo2', models.IntegerField()),
                ('id_usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='molienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('campo1', models.CharField(max_length=255)),
                ('campo2', models.IntegerField()),
                ('id_usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='mlf',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='DEST',
        ),
        migrations.DeleteModel(
            name='MLF',
        ),
    ]
